test_dataset:
  dataset:
    name: image-folder
    args:
      root_path: ./load/dataset/Gt_detail_bmp_test
  wrapper:
    name: sr-implicit-downsampled
    args:
      scale_min: 6
  batch_size: 1
eval_type:
eval_bsize: 30000

data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}